version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
      - cd ./node_modules/.bin && ls
  build:
    commands:
      - echo Building the React app...
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
